title = "Life Science Club"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Life Science Club"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  facebook = "https://www.facebook.com/"
  instagram = "https://www.instagram.com/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/dawson_banner.jpeg"
  recent_posts_number = 2